-- Zadanie 1 --
SELECT NAZWISKO,CONCAT(LEFT(ETAT,2),ID_PRAC) AS KOD FROM PRACOWNICY;

-- Zadanie 2 --
SELECT NAZWISKO,REPLACE(REPLACE(REPLACE(NAZWISKO,'m','X'),'l','X'),'k','X') AS WOJNA_LITEROM FROM Pracownicy
ORDER BY WOJNA_LITEROM ASC;

-- Zadanie 3 --
SELECT NAZWISKO FROM Pracownicy WHERE SUBSTRING(NAZWISKO,1,LEN(NAZWISKO)/2) LIKE '%[Ll]%';

-- Zadanie 4 --
SELECT NAZWISKO,CAST(ROUND(PLACA_POD*1.15,0) AS INT) AS PODWYZKA FROM Pracownicy;

-- Zadanie 5 --
SELECT
	NAZWISKO,
	PLACA_POD,
	PLACA_POD*0.2 AS INWESTYCJA,
	(PLACA_POD*0.2)*POWER(1+0.1, 10) AS KAPITALIZACJA,
	((PLACA_POD*0.2)*POWER(1+0.1, 10)-PLACA_POD*0.2) AS ZYSK
FROM Pracownicy;

-- Zadanie 6 --
SELECT NAZWISKO, ZATRUDNIONY, DATEDIFF(year,ZATRUDNIONY,'2000-01-01') AS STAZ FROM Pracownicy;

-- Zadanie 7 --
SELECT
	NAZWISKO,
	CONCAT(DATENAME(MONTH,ZATRUDNIONY),', ',DATEPART(MONTH,ZATRUDNIONY),' ',DATEPART(year,ZATRUDNIONY)) AS DATA_ZATRUDNIANIA
FROM Pracownicy
WHERE ID_ZESP=20;

-- Zadanie 8 --
SELECT DATENAME(WEEKDAY ,GETDATE()) AS DATENAZWA;

-- Zadanie 9 --
SELECT
	NAZWA,
	ADRES,
CASE
	WHEN ADRES LIKE '%Strzelecka%' THEN 'STARE MIASTO'
	WHEN ADRES LIKE '%PIOTROWO%' THEN 'NOWE MIASTO'
	WHEN ADRES LIKE '%WIENIAWSKIEGO%' THEN 'SOLACZ'
	WHEN ADRES LIKE '%MIELZYNSKIEGO%' THEN 'STARE MIASTO'
END
FROM Zespoly;

-- Zadanie 10 --
SELECT
	NAZWISKO,PLACA_POD,
CASE
	WHEN PLACA_POD > 1590 THEN 'Powy¿ej 1590 zl'
	WHEN PLACA_POD = 1590 THEN 'Dok³adnie 1590 zl'
	WHEN PLACA_POD < 1590 THEN 'Poni¿ej 1590 zl'
END AS PROG
FROM Pracownicy;

-- Zadanie 11 --
-- Nie ma? --

-- Zadanie 12 --
SELECT Etat FROM Pracownicy WHERE DATEPART(year,ZATRUDNIONY)=1992
INTERSECT
SELECT Etat FROM Pracownicy WHERE DATEPART(year,ZATRUDNIONY)=1993;

-- Zadanie 13 --
SELECT ID_ZESP
FROM Zespoly
WHERE NOT EXISTS (
	SELECT ID_ZESP
	FROM Pracownicy
	WHERE Pracownicy.ID_ZESP=Zespoly.ID_ZESP
);

-- Zadanie 14 --
SELECT NAZWISKO, PLACA_POD, 'Powy¿ej 1590 z³' AS PROG FROM Pracownicy WHERE PLACA_POD>1590
UNION
SELECT NAZWISKO, PLACA_POD, 'Poni¿ej 1590 z³' AS PROG FROM Pracownicy WHERE PLACA_POD<1590
UNION
SELECT NAZWISKO, PLACA_POD, 'Dok³adnie 1590 z³' AS PROG FROM Pracownicy WHERE PLACA_POD=1590;